db:
  image: mysql
  expose:
    - "3306"
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: keystone  
    MYSQL_DATABASE: keystone
    MYSQL_USER: keystone
    MYSQL_PASSWORD: keystone

keystone-spassword:
  build: .
  links:
    - db
  ports:
    - "5001:5000"
  #command: keystone-all
  #/etc/keystone/keystone.conf:
  #   connection = mysql://keystone:keystone@localhost/keystone


